run:
	@uvicorn Aulas.APIs.FastAPI.Desafio.main:app --reload

create-migrations:
	@PYTHONPATH = $PYTHONPATH: $(pwd) alembic revision --autogenerate -m $(d)

run-migrations:
	@PYTHONPATH = $PYTHONPATH: $(pwd) alembic upgrade head